### ISSUE TITLE
Error in step-3 at  run  updated main.js

### ISSUE THREAD

**Issue by AliBesharati** [googlecodelabs/transport-tracker-codelab#3]
my npm-debug.log ...

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'main' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'premain', 'main', 'postmain' ]
5 info lifecycle transport-tracker-server@1.0.0~premain: transport-tracker-server@1.0.0
6 silly lifecycle transport-tracker-server@1.0.0~premain: no script for premain, continuing
7 info lifecycle transport-tracker-server@1.0.0~main: transport-tracker-server@1.0.0
8 verbose lifecycle transport-tracker-server@1.0.0~main: unsafe-perm in lifecycle true
9 verbose lifecycle transport-tracker-server@1.0.0~main: PATH: /usr/local/nvm/versions/node/v6.9.2/lib/node_modules/npm/bin/node-gyp-bin:/home/bnalinia/transport-tracker-server/node_modules/.bin:/usr/local/nvm/versions/node/v6.9.2/bin:/google/google-cloud-sdk/bin:/home/bnalinia/gopath/bin:/google/gopath/bin:/usr/local/go/bin:/gradle-2.12/bin:/apache-maven-3.3.9/bin:/google/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/nvm/versions/node/v6.9.2/bin:/google/go_appengine:/google/google_appengine
10 verbose lifecycle transport-tracker-server@1.0.0~main: CWD: /home/bnalinia/transport-tracker-server
11 silly lifecycle transport-tracker-server@1.0.0~main: Args: [ '-c', 'node main.js' ]
12 silly lifecycle transport-tracker-server@1.0.0~main: Returned: code: 1  signal: null
13 info lifecycle transport-tracker-server@1.0.0~main: Failed to exec main script
14 verbose stack Error: transport-tracker-server@1.0.0 main: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v6.9.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid transport-tracker-server@1.0.0
16 verbose cwd /home/bnalinia/transport-tracker-server
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/local/nvm/versions/node/v6.9.2/bin/node" "/usr/bin/npm" "run" "main"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error transport-tracker-server@1.0.0 main: `node main.js`
22 error Exit status 1
23 error Failed at the transport-tracker-server@1.0.0 main script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the transport-tracker-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs transport-tracker-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls transport-tracker-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ghzoan** [comment]
same here :(

**Comment by naeemjawaid** [comment]
Updating npm worked for me.
