### ISSUE TITLE
backend run main

### ISSUE THREAD

**Issue by ghzoan** [googlecodelabs/transport-tracker-codelab#4]
I'm working with a lot of errors from 1 week, every time i got new errors 

please help

In the MAP step the shell stuck !

 transport-tracker-server@1.0.0 main /home/ghzoan/transport-tracker/backend
> node main.js

module.js:529
    throw err;
    ^

Error: Cannot find module './paths.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ghzoan/transport-tracker/backend/main.js:53:26)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! transport-tracker-server@1.0.0 main: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the transport-tracker-server@1.0.0 main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
---------------------

when open map index got 

index.js:24  Uncaught SyntaxError: Unexpected token <

maps.googleapis.com/…raries=geometry:101 Uncaught 
Qb
message
"initMap is not a function"

"InvalidValueError"

please help !

**Comment by Nanodt** [comment]
Same error here

**Comment by skanel** [comment]
same error here

**Comment by Soundbytes** [comment]
Solution: 
In cloud shell cd into the project folder then run the command:
`npm run generate_paths`
this will create the missing paths.json file.

**Comment by juanjzb** [comment]
That happens when you have not executed the command> npm run generate_paths

After that, the script will generate a new file, with al routes.

**Comment by jhonatan6794** [comment]
Help!

npm ERR! missing script: main
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jhonatan6794/.npm/_logs/2020-06-25T19_29_06_795Z-debug.log
jhonatan6794@cloudshell:~/transport-tracker/transport-tracker-admin (road-in-way)$
